name: Run all tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-scope: [lint, unit]
        node-version: [12.14.1]

    steps:
      - uses: actions/checkout@v1
      - name: Get nodejs version for test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm cache clean --force
          rm -rf ~/.npm node_modules
          npm i
        env:
          CI: true

      - name: Lint's checks
        if: ${{ matrix.test-scope == 'lint' }}
        run: |
          npm run lint
          sh ${{ github.workspace }}/tools/publish-styleguide.sh
        env:
          CI: true

      - name: Run tests
        if: ${{ matrix.test-scope == 'unit' }}
        run: |
          npm run test:coverage
          npm run compile
        env:
          CI: true

      - name: Run gemini
        if: ${{ matrix.test-scope == 'gemini' }}
        run: |
          npm run sauce-connect
          cat ${{ github.workspace }}/.gemini.js
          export ALL_BROWSERS=1 ALL_SIZES=1
          npm run gemini-ci
          kill -9 `lsof -i :4445 -t`
        env:
          CI: true
        
      - name: Send gemini's error log
        if: ${{ matrix.test-scope == 'gemini' && failure() }}
        run: |
          sh ${{ github.workspace }}/tools/publish-gemini-report.sh
        env:
          CI: true

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/.publish
